### ISSUE TITLE
fix headings

### ISSUE THREAD

**Issue by colingraydon** [colingraydon/notecard-app#1]
First issue. Change Box divs to Headings where applicable.

**Comment by ELFrancisco4** [comment]
Hello. This issue isnt very specific. Will every instance of a Box div be changed to a Heading?

**Comment by colingraydon** [comment]
Hello, I mostly just opened this issue as a first issue for this project - sorry it wasn't very specific. I've already addressed it - it was a minor styling change.

**Comment by ELFrancisco4** [comment]
> Hello, I mostly just opened this issue as a first issue for this project - sorry it wasn't very specific. I've already addressed it - it was a minor styling change.

All right no problem. Happy hacking
